name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  check_and_execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - config-service
          # Add more services here
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node
        run: |
          nvm install 18.19
          nvm use 18.19

      - name: Check for modifications in microservice
        run: |
          if git diff --name-only HEAD^ | grep -q "^${{{ matrix.service }}/"; then
            echo "Changes detected in ${{ matrix.service }}"
            cd ${{ matrix.service }} || exit 1
            # Run your commands here for each microservice
            cp ../.env .
            node -v
            npm i
            sudo npm install -g serverless
            sudo npm install --save-dev serverless-plugin-typescript
            serverless deploy --config serverless-dev.yml
            pwd
            ls
            cd ..
          else
            echo "No changes detected in ${{ matrix.service }}"
          fi
